# Generated by Django 3.0.4 on 2020-03-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questiondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('t1', models.TextField()),
                ('o1', models.TextField()),
                ('t2', models.TextField()),
                ('o2', models.TextField()),
                ('t3', models.TextField()),
                ('o3', models.TextField()),
                ('t4', models.TextField()),
                ('o4', models.TextField()),
                ('t5', models.TextField()),
                ('o5', models.TextField()),
                ('t6', models.TextField()),
                ('o6', models.TextField()),
                ('t7', models.TextField()),
                ('o7', models.TextField()),
                ('t8', models.TextField()),
                ('o8', models.TextField()),
                ('t9', models.TextField()),
                ('o9', models.TextField()),
                ('t10', models.TextField()),
                ('o10', models.TextField()),
            ],
        ),
    ]
